# SPDX-FileCopyrightText: 2020 Efabless Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# SPDX-License-Identifier: Apache-2.0

# This is a basic workflow to help you get started with Actions
name: Auto Update Caravel Lite

# Controls when the action will run. 
on:
  # Trigger the workflow on push to master branch
  push:
    branches:
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            name: id_rsa # optional
            known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Update Caravel Lite
        run: |
          git clone --depth=1 https://github.com/Manarabdelaty/caravel-lite.git
          cd caravel-lite
          rm -rf caravel-lite/*
          git init
          git checkout -b main
          git pull https://github.com/efabless/caravel master
          git filter-repo --path openlane/user_project_wrapper_empty --path openlane/Makefile --path gds/user_project_wrapper_empty.gds.gz --path lef/user_project_wrapper.lef --path verilog/ --path info.yaml --path Makefile --path scripts/ --path utils/ --path LICENSE --path manifest --force
          git config --global user.email "manarabdelatty@aucegypt.edu"
          git config --global user.name "manarabdelaty"
          git remote add caravel_lite https://github.com/Manarabdelaty/caravel-lite.git
          git push --force caravel_lite main
